name: Producition testing

on:
  push:
    branches:
      - main

jobs:
  
  test-the-code:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Run tests
      - name: Run tests
        run: yarn test
